name = "blask"
version = "0.0.2"
target = "javascript"

description = "A UI component library for Lustre"
licences = ["MIT"]
repository = { type = "github", user = "loipesmas", repo = "blask" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.3.1 and < 5.0.0"
sketch = ">= 3.1.1 and < 4.0.0"
gleroglero = ">= 1.1.0 and < 2.0.0"
sketch_lustre = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
